// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmu626fgi1Hxx7ZRhgkv7JwKFCX1ZOg8',
    appId: '1:18934136027:android:4b52fbca97cb8ef3f9e0fe',
    messagingSenderId: '18934136027',
    projectId: 'parking-db-b805f',
    databaseURL: 'https://parking-db-b805f-default-rtdb.firebaseio.com',
    storageBucket: 'parking-db-b805f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT45ZsAOXVHVrG36JDJaXI1-zhjzd1YwA',
    appId: '1:18934136027:ios:9d815dc0a6a86386f9e0fe',
    messagingSenderId: '18934136027',
    projectId: 'parking-db-b805f',
    databaseURL: 'https://parking-db-b805f-default-rtdb.firebaseio.com',
    storageBucket: 'parking-db-b805f.appspot.com',
    iosBundleId: 'com.example.buildingapp',
  );
}
